/*
 * This file is generated by jOOQ.
 */
package de.omilke.banking.persistence.jooq.meta.tables


import de.omilke.banking.persistence.jooq.meta.Public
import de.omilke.banking.persistence.jooq.meta.indexes.IDX_ENTRY_DATE
import de.omilke.banking.persistence.jooq.meta.keys.CONSTRAINT_3
import de.omilke.banking.persistence.jooq.meta.tables.records.EntryRecord

import java.math.BigDecimal
import java.time.LocalDate

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class Entry(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, EntryRecord>?,
    parentPath: InverseForeignKey<out Record, EntryRecord>?,
    aliased: Table<EntryRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<EntryRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>PUBLIC.ENTRY</code>
         */
        val ENTRY: Entry = Entry()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<EntryRecord> = EntryRecord::class.java

    /**
     * The column <code>PUBLIC.ENTRY.ID</code>.
     */
    val ID: TableField<EntryRecord, Long?> = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>PUBLIC.ENTRY.AMOUNT</code>.
     */
    val AMOUNT: TableField<EntryRecord, BigDecimal?> = createField(DSL.name("AMOUNT"), SQLDataType.DECIMAL(12, 2), this, "")

    /**
     * The column <code>PUBLIC.ENTRY.ENTRYDATE</code>.
     */
    val ENTRYDATE: TableField<EntryRecord, LocalDate?> = createField(DSL.name("ENTRYDATE"), SQLDataType.LOCALDATE, this, "")

    /**
     * The column <code>PUBLIC.ENTRY.COMMENT</code>.
     */
    val COMMENT: TableField<EntryRecord, String?> = createField(DSL.name("COMMENT"), SQLDataType.VARCHAR, this, "")

    /**
     * The column <code>PUBLIC.ENTRY.CATEGORY</code>.
     */
    val CATEGORY: TableField<EntryRecord, String?> = createField(DSL.name("CATEGORY"), SQLDataType.VARCHAR, this, "")

    /**
     * The column <code>PUBLIC.ENTRY.SAVING</code>.
     */
    val SAVING: TableField<EntryRecord, Boolean?> = createField(DSL.name("SAVING"), SQLDataType.BOOLEAN, this, "")

    /**
     * The column <code>PUBLIC.ENTRY.SEQUENCE</code>.
     */
    val SEQUENCE: TableField<EntryRecord, Int?> = createField(DSL.name("SEQUENCE"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>PUBLIC.ENTRY.ORDERINDEX</code>.
     */
    val ORDERINDEX: TableField<EntryRecord, Int?> = createField(DSL.name("ORDERINDEX"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>PUBLIC.ENTRY.ENTRYYEAR</code>.
     */
    val ENTRYYEAR: TableField<EntryRecord, Int?> = createField(DSL.name("ENTRYYEAR"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>PUBLIC.ENTRY.ENTRYMONTH</code>.
     */
    val ENTRYMONTH: TableField<EntryRecord, Int?> = createField(DSL.name("ENTRYMONTH"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>PUBLIC.ENTRY.ENTRYDAY</code>.
     */
    val ENTRYDAY: TableField<EntryRecord, Int?> = createField(DSL.name("ENTRYDAY"), SQLDataType.INTEGER, this, "")

    private constructor(alias: Name, aliased: Table<EntryRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<EntryRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<EntryRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>PUBLIC.ENTRY</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>PUBLIC.ENTRY</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>PUBLIC.ENTRY</code> table reference
     */
    constructor(): this(DSL.name("ENTRY"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(IDX_ENTRY_DATE)
    override fun getIdentity(): Identity<EntryRecord, Long?> = super.getIdentity() as Identity<EntryRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<EntryRecord> = CONSTRAINT_3
    override fun `as`(alias: String): Entry = Entry(DSL.name(alias), this)
    override fun `as`(alias: Name): Entry = Entry(alias, this)
    override fun `as`(alias: Table<*>): Entry = Entry(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Entry = Entry(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Entry = Entry(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Entry = Entry(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Entry = Entry(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Entry = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Entry = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Entry = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Entry = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Entry = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Entry = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Entry = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Entry = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Entry = where(DSL.notExists(select))
}
