/*
 * This file is generated by jOOQ.
 */
package de.omilke.banking.persistence.jooq.meta.tables


import de.omilke.banking.persistence.jooq.meta.Public
import de.omilke.banking.persistence.jooq.meta.keys.CONSTRAINT_D
import de.omilke.banking.persistence.jooq.meta.tables.records.RecurringEntryRecord

import java.math.BigDecimal
import java.time.LocalDate

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row10
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class RecurringEntry(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, RecurringEntryRecord>?,
    aliased: Table<RecurringEntryRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<RecurringEntryRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>PUBLIC.RECURRING_ENTRY</code>
         */
        val RECURRING_ENTRY = RecurringEntry()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<RecurringEntryRecord> = RecurringEntryRecord::class.java

    /**
     * The column <code>PUBLIC.RECURRING_ENTRY.ID</code>.
     */
    val ID: TableField<RecurringEntryRecord, Long?> = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>PUBLIC.RECURRING_ENTRY.AMOUNT</code>.
     */
    val AMOUNT: TableField<RecurringEntryRecord, BigDecimal?> = createField(DSL.name("AMOUNT"), SQLDataType.DECIMAL(12, 2), this, "")

    /**
     * The column <code>PUBLIC.RECURRING_ENTRY.STARTOFRECURRENCE</code>.
     */
    val STARTOFRECURRENCE: TableField<RecurringEntryRecord, LocalDate?> = createField(DSL.name("STARTOFRECURRENCE"), SQLDataType.LOCALDATE, this, "")

    /**
     * The column <code>PUBLIC.RECURRING_ENTRY.LASTRECURRENCE</code>.
     */
    val LASTRECURRENCE: TableField<RecurringEntryRecord, LocalDate?> = createField(DSL.name("LASTRECURRENCE"), SQLDataType.LOCALDATE, this, "")

    /**
     * The column <code>PUBLIC.RECURRING_ENTRY.COMMENT</code>.
     */
    val COMMENT: TableField<RecurringEntryRecord, String?> = createField(DSL.name("COMMENT"), SQLDataType.VARCHAR(2147483647), this, "")

    /**
     * The column <code>PUBLIC.RECURRING_ENTRY.CATEGORY</code>.
     */
    val CATEGORY: TableField<RecurringEntryRecord, String?> = createField(DSL.name("CATEGORY"), SQLDataType.VARCHAR(2147483647), this, "")

    /**
     * The column <code>PUBLIC.RECURRING_ENTRY.SAVING</code>.
     */
    val SAVING: TableField<RecurringEntryRecord, Boolean?> = createField(DSL.name("SAVING"), SQLDataType.BOOLEAN, this, "")

    /**
     * The column <code>PUBLIC.RECURRING_ENTRY.SEQUENCE</code>.
     */
    val SEQUENCE: TableField<RecurringEntryRecord, Int?> = createField(DSL.name("SEQUENCE"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>PUBLIC.RECURRING_ENTRY.ORDERINDEX</code>.
     */
    val ORDERINDEX: TableField<RecurringEntryRecord, Int?> = createField(DSL.name("ORDERINDEX"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>PUBLIC.RECURRING_ENTRY.RECURRENCESTRATEGY</code>.
     */
    val RECURRENCESTRATEGY: TableField<RecurringEntryRecord, String?> = createField(DSL.name("RECURRENCESTRATEGY"), SQLDataType.VARCHAR(2147483647), this, "")

    private constructor(alias: Name, aliased: Table<RecurringEntryRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<RecurringEntryRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>PUBLIC.RECURRING_ENTRY</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>PUBLIC.RECURRING_ENTRY</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>PUBLIC.RECURRING_ENTRY</code> table reference
     */
    constructor(): this(DSL.name("RECURRING_ENTRY"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, RecurringEntryRecord>): this(Internal.createPathAlias(child, key), child, key, RECURRING_ENTRY, null)
    override fun getSchema(): Schema = Public.PUBLIC
    override fun getIdentity(): Identity<RecurringEntryRecord, Long?> = super.getIdentity() as Identity<RecurringEntryRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<RecurringEntryRecord> = CONSTRAINT_D
    override fun getKeys(): List<UniqueKey<RecurringEntryRecord>> = listOf(CONSTRAINT_D)
    override fun `as`(alias: String): RecurringEntry = RecurringEntry(DSL.name(alias), this)
    override fun `as`(alias: Name): RecurringEntry = RecurringEntry(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): RecurringEntry = RecurringEntry(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): RecurringEntry = RecurringEntry(name, null)

    // -------------------------------------------------------------------------
    // Row10 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row10<Long?, BigDecimal?, LocalDate?, LocalDate?, String?, String?, Boolean?, Int?, Int?, String?> = super.fieldsRow() as Row10<Long?, BigDecimal?, LocalDate?, LocalDate?, String?, String?, Boolean?, Int?, Int?, String?>
}
