/*
 * This file is generated by jOOQ.
 */
package de.omilke.banking.persistence.jooq.meta.tables


import de.omilke.banking.persistence.jooq.meta.Public
import de.omilke.banking.persistence.jooq.meta.keys.CONSTRAINT_D
import de.omilke.banking.persistence.jooq.meta.tables.records.RecurringEntryRecord

import java.math.BigDecimal
import java.time.LocalDate

import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class RecurringEntry(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, RecurringEntryRecord>?,
    parentPath: InverseForeignKey<out Record, RecurringEntryRecord>?,
    aliased: Table<RecurringEntryRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<RecurringEntryRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>PUBLIC.RECURRING_ENTRY</code>
         */
        val RECURRING_ENTRY: RecurringEntry = RecurringEntry()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<RecurringEntryRecord> = RecurringEntryRecord::class.java

    /**
     * The column <code>PUBLIC.RECURRING_ENTRY.ID</code>.
     */
    val ID: TableField<RecurringEntryRecord, Long?> = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>PUBLIC.RECURRING_ENTRY.AMOUNT</code>.
     */
    val AMOUNT: TableField<RecurringEntryRecord, BigDecimal?> = createField(DSL.name("AMOUNT"), SQLDataType.DECIMAL(12, 2), this, "")

    /**
     * The column <code>PUBLIC.RECURRING_ENTRY.STARTOFRECURRENCE</code>.
     */
    val STARTOFRECURRENCE: TableField<RecurringEntryRecord, LocalDate?> = createField(DSL.name("STARTOFRECURRENCE"), SQLDataType.LOCALDATE, this, "")

    /**
     * The column <code>PUBLIC.RECURRING_ENTRY.LASTRECURRENCE</code>.
     */
    val LASTRECURRENCE: TableField<RecurringEntryRecord, LocalDate?> = createField(DSL.name("LASTRECURRENCE"), SQLDataType.LOCALDATE, this, "")

    /**
     * The column <code>PUBLIC.RECURRING_ENTRY.COMMENT</code>.
     */
    val COMMENT: TableField<RecurringEntryRecord, String?> = createField(DSL.name("COMMENT"), SQLDataType.VARCHAR, this, "")

    /**
     * The column <code>PUBLIC.RECURRING_ENTRY.CATEGORY</code>.
     */
    val CATEGORY: TableField<RecurringEntryRecord, String?> = createField(DSL.name("CATEGORY"), SQLDataType.VARCHAR, this, "")

    /**
     * The column <code>PUBLIC.RECURRING_ENTRY.SAVING</code>.
     */
    val SAVING: TableField<RecurringEntryRecord, Boolean?> = createField(DSL.name("SAVING"), SQLDataType.BOOLEAN, this, "")

    /**
     * The column <code>PUBLIC.RECURRING_ENTRY.SEQUENCE</code>.
     */
    val SEQUENCE: TableField<RecurringEntryRecord, Int?> = createField(DSL.name("SEQUENCE"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>PUBLIC.RECURRING_ENTRY.ORDERINDEX</code>.
     */
    val ORDERINDEX: TableField<RecurringEntryRecord, Int?> = createField(DSL.name("ORDERINDEX"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>PUBLIC.RECURRING_ENTRY.RECURRENCESTRATEGY</code>.
     */
    val RECURRENCESTRATEGY: TableField<RecurringEntryRecord, String?> = createField(DSL.name("RECURRENCESTRATEGY"), SQLDataType.VARCHAR, this, "")

    private constructor(alias: Name, aliased: Table<RecurringEntryRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<RecurringEntryRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<RecurringEntryRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>PUBLIC.RECURRING_ENTRY</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>PUBLIC.RECURRING_ENTRY</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>PUBLIC.RECURRING_ENTRY</code> table reference
     */
    constructor(): this(DSL.name("RECURRING_ENTRY"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIdentity(): Identity<RecurringEntryRecord, Long?> = super.getIdentity() as Identity<RecurringEntryRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<RecurringEntryRecord> = CONSTRAINT_D
    override fun `as`(alias: String): RecurringEntry = RecurringEntry(DSL.name(alias), this)
    override fun `as`(alias: Name): RecurringEntry = RecurringEntry(alias, this)
    override fun `as`(alias: Table<*>): RecurringEntry = RecurringEntry(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): RecurringEntry = RecurringEntry(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): RecurringEntry = RecurringEntry(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): RecurringEntry = RecurringEntry(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): RecurringEntry = RecurringEntry(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): RecurringEntry = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): RecurringEntry = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): RecurringEntry = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): RecurringEntry = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): RecurringEntry = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): RecurringEntry = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): RecurringEntry = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): RecurringEntry = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): RecurringEntry = where(DSL.notExists(select))
}
