/*
 * This file is generated by jOOQ.
 */
package de.omilke.banking.persistence.jooq.meta.tables.references


import de.omilke.banking.persistence.jooq.meta.tables.Entry
import de.omilke.banking.persistence.jooq.meta.tables.RecurringEntry



/**
 * The table <code>PUBLIC.ENTRY</code>.
 */
val ENTRY = Entry.ENTRY

/**
 * The table <code>PUBLIC.RECURRING_ENTRY</code>.
 */
val RECURRING_ENTRY = RecurringEntry.RECURRING_ENTRY
