/*
 * This file is generated by jOOQ.
 */
package de.omilke.banking.persistence.jooq.meta.indexes


import de.omilke.banking.persistence.jooq.meta.tables.Entry

import org.jooq.Index
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// INDEX definitions
// -------------------------------------------------------------------------

val IDX_ENTRY_DATE: Index = Internal.createIndex(DSL.name("IDX_ENTRY_DATE"), Entry.ENTRY, arrayOf(Entry.ENTRY.ENTRYDATE), false)
