/*
 * This file is generated by jOOQ.
 */
package de.omilke.banking.persistence.jooq.meta.tables.records;


import de.omilke.banking.persistence.jooq.meta.tables.Entry;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;

import java.math.BigDecimal;
import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class EntryRecord extends UpdatableRecordImpl<EntryRecord> implements Record11<Long, BigDecimal, LocalDate, String, String, Boolean, Integer, Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = 105996039;

    /**
     * Setter for <code>PUBLIC.ENTRY.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.ENTRY.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.ENTRY.AMOUNT</code>.
     */
    public void setAmount(BigDecimal value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.ENTRY.AMOUNT</code>.
     */
    public BigDecimal getAmount() {
        return (BigDecimal) get(1);
    }

    /**
     * Setter for <code>PUBLIC.ENTRY.ENTRYDATE</code>.
     */
    public void setEntrydate(LocalDate value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.ENTRY.ENTRYDATE</code>.
     */
    public LocalDate getEntrydate() {
        return (LocalDate) get(2);
    }

    /**
     * Setter for <code>PUBLIC.ENTRY.COMMENT</code>.
     */
    public void setComment(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.ENTRY.COMMENT</code>.
     */
    public String getComment() {
        return (String) get(3);
    }

    /**
     * Setter for <code>PUBLIC.ENTRY.CATEGORY</code>.
     */
    public void setCategory(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.ENTRY.CATEGORY</code>.
     */
    public String getCategory() {
        return (String) get(4);
    }

    /**
     * Setter for <code>PUBLIC.ENTRY.SAVING</code>.
     */
    public void setSaving(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>PUBLIC.ENTRY.SAVING</code>.
     */
    public Boolean getSaving() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>PUBLIC.ENTRY.SEQUENCE</code>.
     */
    public void setSequence(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>PUBLIC.ENTRY.SEQUENCE</code>.
     */
    public Integer getSequence() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>PUBLIC.ENTRY.ORDERINDEX</code>.
     */
    public void setOrderindex(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>PUBLIC.ENTRY.ORDERINDEX</code>.
     */
    public Integer getOrderindex() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>PUBLIC.ENTRY.YEAR</code>.
     */
    public void setYear(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>PUBLIC.ENTRY.YEAR</code>.
     */
    public Integer getYear() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>PUBLIC.ENTRY.MONTH</code>.
     */
    public void setMonth(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>PUBLIC.ENTRY.MONTH</code>.
     */
    public Integer getMonth() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>PUBLIC.ENTRY.DAY</code>.
     */
    public void setDay(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>PUBLIC.ENTRY.DAY</code>.
     */
    public Integer getDay() {
        return (Integer) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<Long, BigDecimal, LocalDate, String, String, Boolean, Integer, Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<Long, BigDecimal, LocalDate, String, String, Boolean, Integer, Integer, Integer, Integer, Integer> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Entry.ENTRY.ID;
    }

    @Override
    public Field<BigDecimal> field2() {
        return Entry.ENTRY.AMOUNT;
    }

    @Override
    public Field<LocalDate> field3() {
        return Entry.ENTRY.ENTRYDATE;
    }

    @Override
    public Field<String> field4() {
        return Entry.ENTRY.COMMENT;
    }

    @Override
    public Field<String> field5() {
        return Entry.ENTRY.CATEGORY;
    }

    @Override
    public Field<Boolean> field6() {
        return Entry.ENTRY.SAVING;
    }

    @Override
    public Field<Integer> field7() {
        return Entry.ENTRY.SEQUENCE;
    }

    @Override
    public Field<Integer> field8() {
        return Entry.ENTRY.ORDERINDEX;
    }

    @Override
    public Field<Integer> field9() {
        return Entry.ENTRY.YEAR;
    }

    @Override
    public Field<Integer> field10() {
        return Entry.ENTRY.MONTH;
    }

    @Override
    public Field<Integer> field11() {
        return Entry.ENTRY.DAY;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public BigDecimal component2() {
        return getAmount();
    }

    @Override
    public LocalDate component3() {
        return getEntrydate();
    }

    @Override
    public String component4() {
        return getComment();
    }

    @Override
    public String component5() {
        return getCategory();
    }

    @Override
    public Boolean component6() {
        return getSaving();
    }

    @Override
    public Integer component7() {
        return getSequence();
    }

    @Override
    public Integer component8() {
        return getOrderindex();
    }

    @Override
    public Integer component9() {
        return getYear();
    }

    @Override
    public Integer component10() {
        return getMonth();
    }

    @Override
    public Integer component11() {
        return getDay();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public BigDecimal value2() {
        return getAmount();
    }

    @Override
    public LocalDate value3() {
        return getEntrydate();
    }

    @Override
    public String value4() {
        return getComment();
    }

    @Override
    public String value5() {
        return getCategory();
    }

    @Override
    public Boolean value6() {
        return getSaving();
    }

    @Override
    public Integer value7() {
        return getSequence();
    }

    @Override
    public Integer value8() {
        return getOrderindex();
    }

    @Override
    public Integer value9() {
        return getYear();
    }

    @Override
    public Integer value10() {
        return getMonth();
    }

    @Override
    public Integer value11() {
        return getDay();
    }

    @Override
    public EntryRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public EntryRecord value2(BigDecimal value) {
        setAmount(value);
        return this;
    }

    @Override
    public EntryRecord value3(LocalDate value) {
        setEntrydate(value);
        return this;
    }

    @Override
    public EntryRecord value4(String value) {
        setComment(value);
        return this;
    }

    @Override
    public EntryRecord value5(String value) {
        setCategory(value);
        return this;
    }

    @Override
    public EntryRecord value6(Boolean value) {
        setSaving(value);
        return this;
    }

    @Override
    public EntryRecord value7(Integer value) {
        setSequence(value);
        return this;
    }

    @Override
    public EntryRecord value8(Integer value) {
        setOrderindex(value);
        return this;
    }

    @Override
    public EntryRecord value9(Integer value) {
        setYear(value);
        return this;
    }

    @Override
    public EntryRecord value10(Integer value) {
        setMonth(value);
        return this;
    }

    @Override
    public EntryRecord value11(Integer value) {
        setDay(value);
        return this;
    }

    @Override
    public EntryRecord values(Long value1, BigDecimal value2, LocalDate value3, String value4, String value5, Boolean value6, Integer value7, Integer value8, Integer value9, Integer value10, Integer value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EntryRecord
     */
    public EntryRecord() {
        super(Entry.ENTRY);
    }

    /**
     * Create a detached, initialised EntryRecord
     */
    public EntryRecord(Long id, BigDecimal amount, LocalDate entrydate, String comment, String category, Boolean saving, Integer sequence, Integer orderindex, Integer year, Integer month, Integer day) {
        super(Entry.ENTRY);

        set(0, id);
        set(1, amount);
        set(2, entrydate);
        set(3, comment);
        set(4, category);
        set(5, saving);
        set(6, sequence);
        set(7, orderindex);
        set(8, year);
        set(9, month);
        set(10, day);
    }
}
