/*
 * This file is generated by jOOQ.
 */
package de.omilke.banking.persistence.jooq.meta.tables.records


import de.omilke.banking.persistence.jooq.meta.tables.RecurringEntry

import java.math.BigDecimal
import java.time.LocalDate

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class RecurringEntryRecord() : UpdatableRecordImpl<RecurringEntryRecord>(RecurringEntry.RECURRING_ENTRY) {

    open var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var amount: BigDecimal?
        set(value): Unit = set(1, value)
        get(): BigDecimal? = get(1) as BigDecimal?

    open var startofrecurrence: LocalDate?
        set(value): Unit = set(2, value)
        get(): LocalDate? = get(2) as LocalDate?

    open var lastrecurrence: LocalDate?
        set(value): Unit = set(3, value)
        get(): LocalDate? = get(3) as LocalDate?

    open var comment: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var category: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    open var saving: Boolean?
        set(value): Unit = set(6, value)
        get(): Boolean? = get(6) as Boolean?

    open var sequence: Int?
        set(value): Unit = set(7, value)
        get(): Int? = get(7) as Int?

    open var orderindex: Int?
        set(value): Unit = set(8, value)
        get(): Int? = get(8) as Int?

    open var recurrencestrategy: String?
        set(value): Unit = set(9, value)
        get(): String? = get(9) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    /**
     * Create a detached, initialised RecurringEntryRecord
     */
    constructor(id: Long? = null, amount: BigDecimal? = null, startofrecurrence: LocalDate? = null, lastrecurrence: LocalDate? = null, comment: String? = null, category: String? = null, saving: Boolean? = null, sequence: Int? = null, orderindex: Int? = null, recurrencestrategy: String? = null): this() {
        this.id = id
        this.amount = amount
        this.startofrecurrence = startofrecurrence
        this.lastrecurrence = lastrecurrence
        this.comment = comment
        this.category = category
        this.saving = saving
        this.sequence = sequence
        this.orderindex = orderindex
        this.recurrencestrategy = recurrencestrategy
        resetTouchedOnNotNull()
    }
}
