/*
 * This file is generated by jOOQ.
 */
package de.omilke.banking.persistence.jooq.meta;


import de.omilke.banking.persistence.jooq.meta.tables.Entry;
import de.omilke.banking.persistence.jooq.meta.tables.RecurringEntry;


/**
 * Convenience access to all tables in PUBLIC
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>PUBLIC.ENTRY</code>.
     */
    public static final Entry ENTRY = Entry.ENTRY;

    /**
     * The table <code>PUBLIC.RECURRING_ENTRY</code>.
     */
    public static final RecurringEntry RECURRING_ENTRY = RecurringEntry.RECURRING_ENTRY;
}
