@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package de.omilke.banking.persistence.jooq.meta.keys


import de.omilke.banking.persistence.jooq.meta.tables.Entry
import de.omilke.banking.persistence.jooq.meta.tables.RecurringEntry
import de.omilke.banking.persistence.jooq.meta.tables.records.EntryRecord
import de.omilke.banking.persistence.jooq.meta.tables.records.RecurringEntryRecord

import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val CONSTRAINT_3: UniqueKey<EntryRecord> = Internal.createUniqueKey(Entry.ENTRY, DSL.name("CONSTRAINT_3"), arrayOf(Entry.ENTRY.ID), true)
val CONSTRAINT_D: UniqueKey<RecurringEntryRecord> = Internal.createUniqueKey(RecurringEntry.RECURRING_ENTRY, DSL.name("CONSTRAINT_D"), arrayOf(RecurringEntry.RECURRING_ENTRY.ID), true)
